name: "Integration Test"

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      id:   codeqltoolchain
      uses: github/codeql-action/init@v2

    - name: Inject
      uses: zbazztian/ghas-customization/inject@main
      with:
        distribution: ${{ steps.codeqltoolchain.outputs.codeql-path }}
        output: codeql-bundle-customized.tar.gz
        script: integrationtest/script.py
