name: "Integration Test"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

#    - name: Initialize CodeQL
#      id:   codeqltoolchain
#      uses: github/codeql-action/init@v2
#
#    - name: Download
#      uses: zbazztian/ghas-customize/download@main
#      with:
#        output: codeql-bundle-customized.tar.gz
#        repo-id: zbazztian/ghas-customize
#        tag-filter: main-*
#        succeed-if-not-exists: true
#
#    - name: Inject
#      id: inject
#      uses: zbazztian/ghas-customize/inject@main
#      with:
#        distribution: ${{ steps.codeqltoolchain.outputs.codeql-path }}
#        output: codeql-bundle-customized.tar.gz
#        script: integrationtest/script.py

    - name: Inject
      id: inject
      run: |
       echo '::set-output name=skipped::true'

    - name: Upload
      if: steps.inject.outputs.skipped == 'true'
      uses: zbazztian/ghas-customize/upload@main
      with:
        distribution: codeql-bundle-customized.tar.gz
